export const shopFilter = [
    {
        id:'dog',
        name:'Dog',
        count:12
    },
    {
        id:'cow',
        name:'Cow',
        count:12
    },
    {
        id:'rabbit',
        name:'rabbit',
        count:12
    },
    {
        id:'mouse',
        name:'mouse',
        count:12
    },
    {
        id:'cat',
        name:'Cat',
        count:12
    }
]