export enum MODAL_TYPES {
    LOGIN = 'LOGIN',
    SIGNUP = 'SIGNUP',
    FORGET_PASSWORD = 'FORGET_PASSWORD',
    OTP_VERIFICATION = 'OTP_VERIFICATION',
    BOOK_CONSULT='BOOK_CONSULT',
    THANK_YOU = 'THANK_YOU',
    JOIN_AS_VET= 'JOIN_AS_VET'
    
}